In [1]:
%load_ext autoreload
%autoreload 2
import os
import sys
module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)
os.getcwd()

import pandas as pd
import matplotlib.pyplot as plt
from src.Cell import group_map

In [2]:
cellData = pd.read_csv("../../data/cellData.csv")
cellData['cell_type'] = cellData.apply(lambda x: group_map(x.Group, x.immuneGroup), axis = 1)

In [3]:
cellData.head()

,SampleID,cellLabelInImage,cellSize,C,Na,Si,P,Ca,Fe,dsDNA,...,Keratin6,HLA_Class_1,Ta,Au,tumorYN,tumorCluster,Group,immuneCluster,immuneGroup,cell_type
0,1,2,146,0,-0.59061,0.875220,-2.57650,-0.806060,-0.2344,-1.308000,...,-0.41883,-0.53738,2.48110,2.32660,1,0,6,0,0,Keratin-positive tumor
1,1,3,102,0,-0.49870,0.017464,-1.22490,-0.501520,-1.3412,0.522570,...,-0.52769,-0.62060,2.30430,2.18710,0,0,2,46,4,CD3-T
2,1,4,43,0,-1.48730,-0.630440,-1.91070,-1.228000,-1.3937,-1.782200,...,0.18774,-1.75050,1.39330,1.47820,1,0,6,0,0,Keratin-positive tumor
3,1,5,211,0,-1.00530,-0.532270,-1.74300,-0.944850,-1.0996,-0.057906,...,-0.30976,-0.52445,1.88680,1.58620,1,0,6,0,0,Keratin-positive tumor
4,1,6,177,0,0.15803,-0.710290,0.51737,-0.096251,-1.0526,0.355020,...,-0.52769,-0.99773,-0.51027,-0.49627,0,0,2,75,6,B

In [4]:
s = cellData.groupby('cell_type')['cellSize'].mean() * 0.39

In [5]:
2048*2048 #pixels

4194304

In [6]:
800*800 #micrometer

640000

In [7]:
cellData.groupby("SampleID")['cellSize'].sum()

SampleID
1     2329530
2     1957951
3     2625774
4     3070219
5     2698745
6     2791960
7     1828432
8     1829578
9     2648515
10    2208763
11    2600419
12    3053989
13    2929341
14    2790993
15    1555532
16    2965213
17    3000901
18    2916907
19    1789537
20    2373166
21    2498951
22    1433292
23    2058508
24    2158108
25    1317995
26    2248387
27    2129248
28    2187492
29    2088799
31    1798222
32    2328136
33     954149
34    1353282
35    2536516
36    1128117
37    2610520
38    2055470
39    1960402
40    1800875
41    1892310
42     454474
43     465901
44     388314
Name: cellSize, dtype: int64

In [8]:
output_data = pd.read_csv("../../data/cell_positions_data/patient9_cell_positions.csv")

In [9]:
output_data[output_data['cell_type'] == "CD8-T"]

            x        y  label cell_type  cell_size_pixel
2      42.120   12.285      4     CD8-T               60
15    199.680   12.285     17     CD8-T              114
23    397.995   14.040     25     CD8-T              290
65     47.775   19.110     73     CD8-T              529
163   326.820   32.175    189     CD8-T              461
...       ...      ...    ...       ...              ...
6063  631.020  777.660   7366     CD8-T              199
6107  504.270  782.730   7418     CD8-T              358
6119  695.175  784.290   7431     CD8-T              350
6121  622.635  784.290   7433     CD8-T              250
6128   77.415  785.070   7440     CD8-T               86

[391 rows x 5 columns]