In [1]:
import pandas as pd

In [2]:
cellData = pd.read_csv("../../david_data/cellData.csv")

In [3]:
cellData.head()

,SampleID,cellLabelInImage,cellSize,C,Na,Si,P,Ca,Fe,dsDNA,...,MPO,Keratin6,HLA_Class_1,Ta,Au,tumorYN,tumorCluster,Group,immuneCluster,immuneGroup
0,1,2,146,0,-0.59061,0.875220,-2.57650,-0.806060,-0.2344,-1.308000,...,-0.13903,-0.41883,-0.53738,2.48110,2.32660,1,0,6,0,0
1,1,3,102,0,-0.49870,0.017464,-1.22490,-0.501520,-1.3412,0.522570,...,-0.13903,-0.52769,-0.62060,2.30430,2.18710,0,0,2,46,4
2,1,4,43,0,-1.48730,-0.630440,-1.91070,-1.228000,-1.3937,-1.782200,...,-0.13903,0.18774,-1.75050,1.39330,1.47820,1,0,6,0,0
3,1,5,211,0,-1.00530,-0.532270,-1.74300,-0.944850,-1.0996,-0.057906,...,-0.13903,-0.30976,-0.52445,1.88680,1.58620,1,0,6,0,0
4,1,6,177,0,0.15803,-0.710290,0.51737,-0.096251,-1.0526,0.355020,...,-0.13903,-0.52769,-0.99773,-0.51027,-0.49627,0,0,2,75,6

In [6]:
cellData[(cellData['Group'] == 2) & (cellData['immuneGroup'] != 0)]

,SampleID,cellLabelInImage,cellSize,C,Na,Si,P,Ca,Fe,dsDNA,...,MPO,Keratin6,HLA_Class_1,Ta,Au,tumorYN,tumorCluster,Group,immuneCluster,immuneGroup
1,1,3,102,0,-0.49870,0.017464,-1.22490,-0.501520,-1.34120,0.52257,...,-0.13903,-0.52769,-0.620600,2.30430,2.18710,0,0,2,46,4
4,1,6,177,0,0.15803,-0.710290,0.51737,-0.096251,-1.05260,0.35502,...,-0.13903,-0.52769,-0.997730,-0.51027,-0.49627,0,0,2,75,6
5,1,7,159,0,-0.13290,-0.796930,-0.19051,-0.188450,-1.08230,1.01370,...,-0.13903,-0.25887,-0.714370,-0.61707,-0.52939,0,0,2,46,4
6,1,8,169,0,-0.91108,-0.562090,-1.96590,-1.246000,-1.27770,-2.11920,...,-0.13903,-0.37733,-0.139860,0.76665,0.74765,0,0,2,36,2
9,1,11,460,0,-0.23337,-0.618280,-0.29608,-0.545790,-1.08400,-0.28830,...,-0.13903,-0.34140,-0.891850,-0.10993,-0.15354,0,0,2,65,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201622,44,1370,217,0,3.98080,0.561980,0.53295,1.114900,-0.28622,0.90017,...,-0.13903,-0.52769,-0.501980,0.88652,0.90247,0,0,2,87,9
201631,44,1381,91,0,4.10850,0.592930,0.92864,1.213900,-0.29377,0.72405,...,-0.13903,-0.52769,-0.076169,0.75328,0.90365,0,0,2,56,12
201632,44,1382,396,0,3.95580,-0.468270,0.41970,1.187300,-0.93473,2.16430,...,-0.13903,-0.52769,-1.152900,1.46560,1.24670,0,0,2,56,12
201637,44,1388,138,0,3.90160,-0.407950,0.95573,1.129200,-0.78905,1.91330,...,-0.13903,-0.52769,-1.494700,-0.59362,-0.25292,0,0,2,56,12
201650,44,1401,109,0,4.28710,-0.779310,2.15440,1.506900,-0.45095,2.63490,...,-0.13903,-0.52769,-1.852900,-0.72709,-0.53959,0,0,2,56,12